user = input("Dear user, Enter your name :- ")
print(user) 
n1 = eval(input(f"Dear {user}, Enter the first number:- ")) 
print(n1) 
n2 = eval(input(f"Dear {user}, Enter the second number:- ")) 
print(n2) 
print(f"Dear {user},\n find the following result:\n Addition = {n1+n2}, Subtraction = {n1-n2}, Multiplication = {n1*n2}, Division = {n1//n2}") 
